WowForum/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WowForum.Models;
using WowForum.Models.APIReturnModels;

namespace WowForum.Controllers
{
    public class CharacterController : BaseController
    {
        public ActionResult CharacterForm()
        {
            CharacterInformationModel model = new CharacterInformationModel();

            return View("CharacterForm", model);
        }

        public ActionResult GetCharacter(CharacterInformationModel characterInfo)
        {
            APIController API = new APIController();
            CharacterInfoAPIModel model = new CharacterInfoAPIModel();
            model = API.GetCharacter(characterInfo);
            if(model == null)
            {
                TempData["Error"] = "Character not found";
                return RedirectToAction("CharacterForm");
            }
            model.GetCharacterRecode();

            SharedSession["WoWCharacterInfo"] = model;

            return View("CharacterDisplay", model);

        }
    }
}

WowForum/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WowForum.Models;
using WowForum.Models.APIReturnModels;
using WowForum.SQLDAL;

namespace WowForum.Controllers
{
    public class LoginController : BaseController
    {
        public ActionResult LoginForm()
        {
            LoginViewModel model = new LoginViewModel();

            return View("LoginForm", model);
        }

        public ActionResult LoginUser(LoginViewModel loginViewModel)
        {
            IUserDAL userDAL = new UserDAL();
            userDAL.GetUser(loginViewModel.username, loginViewModel.password);

            Session["username"] = loginViewModel.username;

            return View("TempPage");
        }

        public ActionResult CreateUser(NewUserModel userInfo)
        {

            IUserDAL userDAL = new UserDAL();
            var currentUser = userDAL.GetUser(userInfo.Username, userInfo.Password);

            if(currentUser != null)
            {
                return View("TempPage");
            }

            if(SharedSession["WoWCharacterInfo"] != null)
            {
                CharacterInfoAPIModel characterInfo = (CharacterInfoAPIModel)SharedSession["WowCharacterInfo"];
                userDAL.CreateUserWithChar(userInfo, characterInfo);
            }
            else
            {
                userDAL.CreateUserNoChar(userInfo);
            }

            Session["username"] = userInfo.Username;

            return View("TempPage");

        }

        public ActionResult NewUserForm()
        {
            NewUserModel model = new NewUserModel();

            return View("NewUserForm", model);
        }
    }
}

WowForum/Views/Character/CharacterDisplay.cshtml
@model WowForum.Models.APIReturnModels.CharacterInfoAPIModel
@{
    ViewBag.Title = "CharacterDisplay";
}
@Styles.Render("~/Content/CharDisplay.css")
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<h2 class="text-center">Is this you?</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-sm-6 col-lg-offset-4">
            <div class="card hovercard">
                @if (Model.recodedFaction == "Horde")
                {
                    <div class="cardheaderhor">
                    </div>
                }
                else
                {
                    <div class="cardheaderall">
                    </div>
                }

                <div class="avatar">
                    <img alt="" src="@Model.recodedThumbnail">
                </div>
                <div class="info">
                    <div class="title">
                        <a target="_blank" href="">@Model.name</a>
                    </div>
                    <div class="desc">@Model.realm</div>
                    <div class="desc">@Model.recodedRace</div>
                    <div class="desc">@Model.recodedClass</div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="text-center">
    <div class="btn-group">
        <a href="@Url.Action("NewUserForm", "Login")" class="btn btn-primary">Yes</a>
        <a href="@Url.Action("CharacterForm", "Character")" class="btn btn-danger">No</a>
    </div>
</div>

WowForum/Views/Character/CharacterForm.cshtml
@model WowForum.Models.CharacterInformationModel
@{
    ViewBag.Title = "Character Form";
}
@Styles.Render("~/Content/Main.css")

<h2 class="text-center">Identify Character</h2>
<div class="text-center" id="error">@TempData["Error"]</div>
<div class="container" id="CharacterFormCont">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please enter character information</h3>
                </div>
                <div class="panel-body">
                    <fieldset>
                        @using (Html.BeginForm("GetCharacter", "Character", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.name, new { @id = "CharacterName", @name = "Character name", @type = "text", @placeholder = "Name", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.name, "", new { @class = "validation-error" })
                        </div>
                        <div class="form-group">
                            @Html.TextBoxFor(m => m.realm, new { @id = "Realm", @name = "Realm", @type = "text", @placeholder = "Realm", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.name, "", new { @class = "validation-error" })
                        </div>
                            <button class="btn btn-lg btn-success btn-block">Submit</button>
                        }
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>